col_mapping = {
    "aws_period_1": "aws_specifics_period",
    "aws_period_2": "aws_specifics_period",
    "aws_space_1": "aws_specifics_space",
    "aws_space_2": "aws_specifics_space",
    "aws_evidence_1": "aws_specifics_evidence",
    "aws_evidence_2": "aws_specifics_evidence",
    "aws_theme_1": "aws_specifics_themes",
    "aws_theme_2": "aws_specifics_themes",
    "smt_specifics_1": "smt_specifics",
    "smt_specifics_2": "smt_specifics",
    "ha_specifics": "ha_specifics",
    "as_specifics": "as_specifics",
    "rs_specifics": "rs_specifics",
}
